### PR TITLE
Clang Integration

### PR DESCRIPTION
**Pull request by doudou**
Final integration work for the clang importer. This supersedes #28

### CODE REVIEW

**Comment by marvin2k** [comment]
The branch needs to be rebased onto master -- to contain changes from the _orogen_loaders_ branch? Running `rock-replay` after building with clang-importer gives

    /home/mzenzes/TransTerrA/rock/tools/orocos.rb/lib/orocos/base.rb:7:in `<module:Orocos>': uninitialized constant OroGen::ConfigError (NameError)

I don't like to ask other people to do work for me ;-) But would you be so kind? If I start to rebase this I can only mess up...

**Comment by marvin2k** [comment]
The branch needs to be rebased onto master -- to contain changes from the _orogen_loaders_ branch? Running `rock-replay` after building with clang-importer gives

    /home/mzenzes/TransTerrA/rock/tools/orocos.rb/lib/orocos/base.rb:7:in `<module:Orocos>': uninitialized constant OroGen::ConfigError (NameError)

I don't like to ask other people to do work for me ;-) But would you be so kind? If I start to rebase this I can only mess up...

**Comment by doudou** [comment]
> I don't like to ask other people to do work for me ;-) But would you be so kind? If I start to rebase this I can only mess up...

Tssss ... Don't be so shy ;-)

Anyways, merged master in and pushed (for both typelib and orogen). I could build and run the orocos.rb test suite successfully.

**Comment by goldhoorn** [comment]
*pong* okay for all to merge?

**Comment by goldhoorn** [comment]
Got a okay from Sylavin, i merge

**Pull request merged**
