### PR TITLE
Enable QT Support for Orogen deployment.

### PR DESCRIPTION
**Pull request by goldhoorn**
define use_qt within the task_context to instanciate
a QT_application within the main thread.

Added missing include dir for tasks

fixed wrong namespace

argh

### CODE REVIEW

**Comment by doudou** [comment]
I would very much like to avoid special-purpose code like this in orogen. Do you think you could figure out a way to create an API to "tune" code for the generated deployments the way the task context generation already does ?

**Comment by goldhoorn** [comment]
I could add a auto generation block within the main app, this should not be a big deal.
The problem is that i replace the main exec call by a thread which could be done only by a flag.

Nevertheless the ugly part is the extension of the cmake lists to add several code blocks here would make orogen even more ugly (from my point of view).

Unforutnalty QT is kind of special by it's own, there are not many needs for extensions like this for orogen bysides QT (that i can think of) therefore i thought this extension would be okay.

It was needed since we had already the workaround at dfki for GUI apps where the qt.exec call was done within a own thread. But this does not work anymore on macos therefore we need a better integrated way into the toolchain.

This integration is from my point of view clean, even it should only used on some special cases.

**Comment by doudou** [comment]
I just have to take a week or so to let the idea that this ugly thing is the best we can do - or hopefully that I find another solution ;-)

**Comment by goldhoorn** [comment]
Also re-thought about it, it is possible to add generators and build a orogen_qt_plugin which would make the API nicer, but in the end it will to exactly this so. Could do better integration for such things, but in the end it will result in the same. 

In the long run if we think regarding a dynamic-deployer it needs also to know if there is a dependancy to qt. Therefore another deployer can be selected. In the end we need to define this kind of things on the task/spec.  So i would like to go for this solution. If you don't came up with something really nicer ;)

Btw. the link deps can still be handelt (by using_library) but the automocing would need a cmake extension again...

**Comment by goldhoorn** [comment]
@doudou: friendly 'a week' (or so (or exactly)) reminder

**Pull request merged**
