### PR TITLE
Clang integration

### PR DESCRIPTION
**Pull request by marvin2k**
Needed changes for the new [clang-importer](https://github.com/orocos-toolchain/typelib/pull/35) of [typelib](https://github.com/orocos-toolchain/typelib).

### CODE REVIEW

**Comment by doudou** [comment]
Hey. I am on it ... I've made some refactoring to keep gccxml in parallel, I don't believe we can hard-switch to clang like this.

**Comment by marvin2k** [comment]
You mean keeping both importers in parallel for some time-span? Hm... If you write the glue-code ;-)

**Comment by doudou** [comment]
As I said in the private email, I did the work: https://github.com/orocos-toolchain/orogen/tree/clang and https://github.com/orocos-toolchain/typelib/tree/clang.

**Comment by doudou** [comment]
And I would go for a variant of the deprecation policy I proposed on rock-dev:
 - one release with gccxml as default and clang as option
 - one release with clang as default and gccxml as option
 - one release where we delete gccxml

**Comment by marvin2k** [comment]
> As I said in the private email, I did the work...

The osdeps for clang-3.4 are missing

    clang-3.4:
        debian, ubuntu: [llvm-3.4, clang-3.4, libclang-3.4-dev]

> And I would go for a variant of the deprecation policy I proposed on rock-dev:

Do you mean that after three consecutive releases gccxml is gone? Aye, then.

**Comment by doudou** [comment]
Superseded by #32

**Pull request closed without merging**
